/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import connect_db.MyConnection;
import java.awt.Image;
import java.io.File;
import java.sql.Blob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import models.Post;
import models.TimeLine;

/**
 *
 * @author PHUTRAN
 */
public class DetailPostVolunteerForm extends javax.swing.JFrame {

    /**
     * Creates new form DetailPostForm
     */
    private static Post post;
    private static int postId;
    private static int userId;
    private static TimeLine timeLine;
    
    public DetailPostVolunteerForm(int postId, int userId) {
        initComponents();
        this.postId = postId;
        this.userId = userId;
        this.setLocationRelativeTo(null);
        
        loadLogo();
        loadInfoPost(postId);
        loadTimeLine(post.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVolunteer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelGoalPeople = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelRaisePeople = new javax.swing.JLabel();
        btnVolunteerSignUp = new javax.swing.JButton();
        panelDonation = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelRaiseMoney = new javax.swing.JLabel();
        labelGoalMoney = new javax.swing.JLabel();
        btnDonation = new javax.swing.JButton();
        panelHeader = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        labelImagePost = new javax.swing.JLabel();
        labelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTimeLine = new javax.swing.JTable();
        comboBoxDirection = new javax.swing.JComboBox<>();

        panelVolunteer.setBackground(new java.awt.Color(239, 202, 72));

        jLabel3.setText("Số người cần huy động:");

        labelGoalPeople.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        labelGoalPeople.setForeground(new java.awt.Color(17, 25, 205));
        labelGoalPeople.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelGoalPeople.setText("0");
        labelGoalPeople.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setText("Số người đã đăng ký:");

        labelRaisePeople.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        labelRaisePeople.setForeground(new java.awt.Color(17, 205, 58));
        labelRaisePeople.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelRaisePeople.setText("0");

        javax.swing.GroupLayout panelVolunteerLayout = new javax.swing.GroupLayout(panelVolunteer);
        panelVolunteer.setLayout(panelVolunteerLayout);
        panelVolunteerLayout.setHorizontalGroup(
            panelVolunteerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVolunteerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVolunteerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelVolunteerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVolunteerLayout.createSequentialGroup()
                        .addComponent(labelRaisePeople, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelGoalPeople, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelVolunteerLayout.setVerticalGroup(
            panelVolunteerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVolunteerLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(panelVolunteerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelGoalPeople))
                .addGap(20, 20, 20)
                .addGroup(panelVolunteerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelRaisePeople))
                .addGap(26, 26, 26))
        );

        btnVolunteerSignUp.setBackground(new java.awt.Color(235, 35, 35));
        btnVolunteerSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnVolunteerSignUp.setText("Đăng ký");
        btnVolunteerSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolunteerSignUpActionPerformed(evt);
            }
        });

        panelDonation.setBackground(new java.awt.Color(239, 202, 72));

        jLabel5.setText("Số tiền cần huy động:");

        jLabel6.setText("Số tiền đã quyên góp:");

        labelRaiseMoney.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        labelRaiseMoney.setForeground(new java.awt.Color(17, 25, 205));
        labelRaiseMoney.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelRaiseMoney.setText("30000000");

        labelGoalMoney.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        labelGoalMoney.setForeground(new java.awt.Color(17, 205, 58));
        labelGoalMoney.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelGoalMoney.setText("2000000");

        javax.swing.GroupLayout panelDonationLayout = new javax.swing.GroupLayout(panelDonation);
        panelDonation.setLayout(panelDonationLayout);
        panelDonationLayout.setHorizontalGroup(
            panelDonationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDonationLayout.createSequentialGroup()
                .addGroup(panelDonationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDonationLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelRaiseMoney, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                    .addGroup(panelDonationLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelGoalMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        panelDonationLayout.setVerticalGroup(
            panelDonationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDonationLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelDonationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelRaiseMoney))
                .addGap(20, 20, 20)
                .addGroup(panelDonationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelGoalMoney))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        btnDonation.setBackground(new java.awt.Color(235, 35, 35));
        btnDonation.setForeground(new java.awt.Color(255, 255, 255));
        btnDonation.setText("TÔI MUỐN ỦNG HỘ");
        btnDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonationActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(239, 202, 72));

        labelLogo.setText("jLabel1");

        jLabel1.setText("Về chúng tôi");

        jLabel2.setText("Trang chủ");

        panelMain.setBackground(new java.awt.Color(239, 202, 72));

        labelImagePost.setText("jLabel3");

        labelTitle.setBackground(new java.awt.Color(255, 255, 255));
        labelTitle.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(241, 11, 11));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("jLabel3");

        textDescField.setColumns(20);
        textDescField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        textDescField.setRows(5);
        textDescField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(textDescField);

        tableTimeLine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Thời gian", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableTimeLine);
        if (tableTimeLine.getColumnModel().getColumnCount() > 0) {
            tableTimeLine.getColumnModel().getColumn(0).setResizable(false);
            tableTimeLine.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelImagePost, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTitle)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelImagePost, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        comboBoxDirection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xem thông tin tài khoản", "Quản lý hoạt động của bạn", "Đăng bài", "Đăng xuất" }));
        comboBoxDirection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDirectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(comboBoxDirection, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(panelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxDirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolunteerSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolunteerSignUpActionPerformed
        
        VolunteerSignUpForm volunteerSignUpForm = new VolunteerSignUpForm(post.getId(), userId);
        volunteerSignUpForm.setVisible(true);
        volunteerSignUpForm.pack();
        volunteerSignUpForm.setLocationRelativeTo(null);
        volunteerSignUpForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnVolunteerSignUpActionPerformed

    private void btnDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonationActionPerformed
        DonationForm donationForm = new DonationForm(post.getId(), userId);
        donationForm.setVisible(true);
        donationForm.pack();
        donationForm.setLocationRelativeTo(null);
        donationForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnDonationActionPerformed

    private void comboBoxDirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDirectionActionPerformed
        int index = comboBoxDirection.getSelectedIndex();

        if(index == 0) { 
            ProfileForm profileForm = new ProfileForm(userId, "");
            profileForm.setVisible(true);
            profileForm.pack();
            profileForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else if (index == 1) { 
            ManageUserPost manageUserPost = new ManageUserPost(userId);
            manageUserPost.setVisible(true);
            manageUserPost.pack();
            manageUserPost.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else if (index == 2 ) { 
            CreatePost createPostForm = new CreatePost(userId);
            createPostForm.setVisible(true);
            createPostForm.pack();
            createPostForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else { 
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            loginForm.pack();
            loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_comboBoxDirectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void loadLogo() { 
        File logo = new File(System.getProperty("user.dir") + "/src/images/logo.jpg");
        String path = logo.getAbsolutePath();
        ImageIcon myImage = new ImageIcon(path);
        
        Image image = myImage.getImage();
        Image newImage = image.getScaledInstance(labelLogo.getWidth(), labelLogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(newImage);
        labelLogo.setIcon(imageIcon);
    }
    public void loadInfoPost(int postId) {
        System.out.println(postId);
        PreparedStatement ps;
        ResultSet rs;
        String query = "select * from posts " +
                        "left join time_lines " +
                        "on time_lines.pid = posts.id " +
                        "where posts.id = ?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setInt(1, postId);
            
            rs = ps.executeQuery();
            if(rs.next()) { 
                post = new Post(rs.getInt(1), rs.getString(2), rs.getBlob(3), rs.getDouble(4), rs.getDouble(5), rs.getInt(6), rs.getInt(7), rs.getString(8));
                System.out.println(post.toString());
            }
            if(post.getGoalMoney() == 0) { 
                panelMain.add(panelVolunteer);
                panelVolunteer.setBounds(30, 300, 202, 100);
                panelMain.add(btnVolunteerSignUp);
                btnVolunteerSignUp.setBounds(331, 395, 160, 28); 
                
                labelRaisePeople.setText(String.valueOf(post.getRaisePeople()));
                labelGoalPeople.setText(String.valueOf(post.getGoalPeople()));
                
            } else { 
                panelMain.add(panelDonation);
                panelDonation.setBounds(30, 300, 202, 100);
                panelMain.add(btnDonation);
                btnDonation.setBounds(361,395,137,28);
                
                labelRaiseMoney.setText(String.valueOf(post.getRaiseMoney()));
                labelGoalMoney.setText(String.valueOf(post.getGoalMoney()));
            }
            labelTitle.setText(post.getTitle());
            textDescField.setText(post.getDescription());
            textDescField.setEnabled(false);
            
            ImageIcon myImage = null;
            if(post.getImage() != null) { 
                Blob imagePost = post.getImage();
                byte[] imageBytes = imagePost.getBytes(1, (int) imagePost.length());
                myImage = new ImageIcon(imageBytes);
            } else { 
                File nullAvatar = new File(System.getProperty("user.dir") + "/src/images/image-post-null.jpg");
                String path = nullAvatar.getAbsolutePath();
                myImage = new ImageIcon(path);
            }
            Image image = myImage.getImage();
            Image newImage = image.getScaledInstance(labelImagePost.getWidth(), labelImagePost.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(newImage);
            labelImagePost.setIcon(imageIcon);
            this.setTitle(post.getTitle());
        } catch (SQLException ex) {
            Logger.getLogger(DetailPostVolunteerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void loadTimeLine(int postId) { 
        String queryGetTimeLinesByPostId = "select take_place, description, has_done " +
                        "from time_lines " +
                        "where pid = ?";
        PreparedStatement ps;
        ResultSet rs;
        
        try {
            ps = MyConnection.getConnection().prepareStatement(queryGetTimeLinesByPostId);
            ps.setInt(1, postId);
            rs = ps.executeQuery();
            while (rs.next()) {
                DefaultTableModel model = (DefaultTableModel) tableTimeLine.getModel();
                model.addRow(new Object[] { 
                    rs.getString(1),
                    rs.getString(2),
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(DetailPostVolunteerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    } 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailPostVolunteerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailPostVolunteerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailPostVolunteerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailPostVolunteerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailPostVolunteerForm(postId,userId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonation;
    private javax.swing.JButton btnVolunteerSignUp;
    private javax.swing.JComboBox<String> comboBoxDirection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelGoalMoney;
    private javax.swing.JLabel labelGoalPeople;
    private javax.swing.JLabel labelImagePost;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelRaiseMoney;
    private javax.swing.JLabel labelRaisePeople;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelDonation;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelVolunteer;
    private javax.swing.JTable tableTimeLine;
    private javax.swing.JTextArea textDescField;
    // End of variables declaration//GEN-END:variables
}
