package views;


import connect_db.MyConnection;
import java.awt.Image;
import java.io.File;
import java.sql.Blob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import models.Post;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PHUTRAN
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */

    private static int postIdAttention, postIdTop1,postIdTop2,postIdTop3;
    private static int userId = -1;
    public Home(int userId) {
        this.userId = userId;
        initComponents();
        this.setTitle("Trang chủ");
        this.setLocationRelativeTo(null);
        
        panelHeader.add(comboBoxDirection);
        comboBoxDirection.setBounds(489,19,154,26);
        
        panelHeader.add(labelAbout);
        labelAbout.setBounds(404, 24, 67, 16);
        
        panelHeader.add(labelHome);
        labelHome.setBounds(331, 24, 53, 16);

        loadLogo();
        loadPostAttention();
        loadListPost();
    }
    public Home() {
        initComponents();
        panelHeader.remove(comboBoxDirection);
        this.setTitle("Trang chủ");
        this.setLocationRelativeTo(null);
        
       panelHeader.add(labelLogin);
       labelLogin.setBounds(585, 24, 58, 16);
        panelHeader.add(labelAbout);
        labelAbout.setBounds(498, 24, 67, 16);
        panelHeader.add(labelHome);
        labelHome.setBounds(425, 24, 53, 16);

        loadLogo();
        loadPostAttention();
        loadListPost();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHome = new javax.swing.JLabel();
        labelAbout = new javax.swing.JLabel();
        comboBoxDirection = new javax.swing.JComboBox<>();
        labelLogin = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imageAttention = new javax.swing.JLabel();
        titleAttention = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelImageTop1 = new javax.swing.JLabel();
        titlePostTop1 = new javax.swing.JLabel();
        labelImageTop2 = new javax.swing.JLabel();
        titlePostTop2 = new javax.swing.JLabel();
        labelImageTop3 = new javax.swing.JLabel();
        titlePostTop3 = new javax.swing.JLabel();

        labelHome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelHome.setText("Trang chủ");
        labelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelAbout.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelAbout.setText("Về chúng tôi");
        labelAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAboutMouseClicked(evt);
            }
        });

        comboBoxDirection.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        comboBoxDirection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xem tài khoản của bạn", "Quản lý tài khoản", "Đăng bài", "Đăng xuất" }));
        comboBoxDirection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDirectionActionPerformed(evt);
            }
        });

        labelLogin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelLogin.setText("Đăng nhập");
        labelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLoginMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(189, 213, 234));
        panelHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelLogo.setText("jLabel1");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(189, 213, 234));

        imageAttention.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imageAttention.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageAttentionMouseClicked(evt);
            }
        });

        titleAttention.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleAttention.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleAttention.setText("jLabel5");
        titleAttention.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        titleAttention.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        titleAttention.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleAttentionMouseClicked(evt);
            }
        });

        searchField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        searchField.setForeground(new java.awt.Color(153, 153, 153));
        searchField.setText("Tìm kiếm hoạt động");
        searchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFieldFocusLost(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Danh sách các hoạt động");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Bài viết nổi bật");

        labelImageTop1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelImageTop1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImageTop1MouseClicked(evt);
            }
        });

        titlePostTop1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        titlePostTop1.setText("jLabel6");
        titlePostTop1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        titlePostTop1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titlePostTop1MouseClicked(evt);
            }
        });

        labelImageTop2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelImageTop2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImageTop2MouseClicked(evt);
            }
        });

        titlePostTop2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        titlePostTop2.setText("jLabel8");
        titlePostTop2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        titlePostTop2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titlePostTop2MouseClicked(evt);
            }
        });

        labelImageTop3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelImageTop3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImageTop3MouseClicked(evt);
            }
        });

        titlePostTop3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        titlePostTop3.setText("jLabel10");
        titlePostTop3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        titlePostTop3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titlePostTop3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(titleAttention, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                    .addComponent(imageAttention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelImageTop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelImageTop2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelImageTop3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titlePostTop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(titlePostTop2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(titlePostTop3, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imageAttention, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(titleAttention, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(titlePostTop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelImageTop1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelImageTop2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(titlePostTop2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelImageTop3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(titlePostTop3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageAttentionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAttentionMouseClicked
        if(userId > 0) { 
            DetailPostVolunteerForm detailPostVolunteerForm = new DetailPostVolunteerForm(postIdAttention, userId);
            detailPostVolunteerForm.setVisible(true);
            detailPostVolunteerForm.setLocationRelativeTo(null);
            detailPostVolunteerForm.pack();
            detailPostVolunteerForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else { 
            JOptionPane.showMessageDialog(null, "Hãy đăng nhập để xem chi tiết bài viết chi tiết");
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            loginForm.setLocationRelativeTo(null);
            loginForm.pack();
            loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_imageAttentionMouseClicked

    private void titleAttentionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleAttentionMouseClicked
        if(userId > 0) { 
            DetailPostVolunteerForm detailPostVolunteerForm = new DetailPostVolunteerForm(postIdAttention, userId);
            detailPostVolunteerForm.setVisible(true);
            detailPostVolunteerForm.setLocationRelativeTo(null);
            detailPostVolunteerForm.pack();
            detailPostVolunteerForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else { 
            JOptionPane.showMessageDialog(null, "Hãy đăng nhập để xem chi tiết bài viết chi tiết");
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            loginForm.setLocationRelativeTo(null);
            loginForm.pack();
            loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_titleAttentionMouseClicked

    private void labelImageTop1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImageTop1MouseClicked
        if(userId > 0) { 
            DetailPostVolunteerForm detailPostVolunteerForm = new DetailPostVolunteerForm(postIdTop1, userId);
            detailPostVolunteerForm.setVisible(true);
            detailPostVolunteerForm.setLocationRelativeTo(null);
            detailPostVolunteerForm.pack();
            detailPostVolunteerForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else { 
            JOptionPane.showMessageDialog(null, "Hãy đăng nhập để xem chi tiết bài viết chi tiết");
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            loginForm.setLocationRelativeTo(null);
            loginForm.pack();
            loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_labelImageTop1MouseClicked

    private void titlePostTop1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePostTop1MouseClicked
        if(userId > 0) { 
            DetailPostVolunteerForm detailPostVolunteerForm = new DetailPostVolunteerForm(postIdTop1, userId);
            detailPostVolunteerForm.setVisible(true);
            detailPostVolunteerForm.setLocationRelativeTo(null);
            detailPostVolunteerForm.pack();
            detailPostVolunteerForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else { 
            JOptionPane.showMessageDialog(null, "Hãy đăng nhập để xem chi tiết bài viết chi tiết");
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            loginForm.setLocationRelativeTo(null);
            loginForm.pack();
            loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_titlePostTop1MouseClicked

    private void labelImageTop2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImageTop2MouseClicked
        if(userId > 0) { 
            DetailPostVolunteerForm detailPostVolunteerForm = new DetailPostVolunteerForm(postIdTop2, userId);
            detailPostVolunteerForm.setVisible(true);
            detailPostVolunteerForm.setLocationRelativeTo(null);
            detailPostVolunteerForm.pack();
            detailPostVolunteerForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else { 
            JOptionPane.showMessageDialog(null, "Hãy đăng nhập để xem chi tiết bài viết chi tiết");
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            loginForm.setLocationRelativeTo(null);
            loginForm.pack();
            loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }      
    }//GEN-LAST:event_labelImageTop2MouseClicked

    private void titlePostTop2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePostTop2MouseClicked
       if(userId > 0) { 
            DetailPostVolunteerForm detailPostVolunteerForm = new DetailPostVolunteerForm(postIdTop2, userId);
            detailPostVolunteerForm.setVisible(true);
            detailPostVolunteerForm.setLocationRelativeTo(null);
            detailPostVolunteerForm.pack();
            detailPostVolunteerForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else { 
            JOptionPane.showMessageDialog(null, "Hãy đăng nhập để xem chi tiết bài viết chi tiết");
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            loginForm.setLocationRelativeTo(null);
            loginForm.pack();
            loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_titlePostTop2MouseClicked

    private void labelImageTop3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImageTop3MouseClicked
        if(userId > 0) { 
            DetailPostVolunteerForm detailPostVolunteerForm = new DetailPostVolunteerForm(postIdTop3, userId);
            detailPostVolunteerForm.setVisible(true);
            detailPostVolunteerForm.setLocationRelativeTo(null);
            detailPostVolunteerForm.pack();
            detailPostVolunteerForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else { 
            JOptionPane.showMessageDialog(null, "Hãy đăng nhập để xem chi tiết bài viết chi tiết");
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            loginForm.setLocationRelativeTo(null);
            loginForm.pack();
            loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_labelImageTop3MouseClicked

    private void titlePostTop3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePostTop3MouseClicked
        if(userId > 0) { 
            DetailPostVolunteerForm detailPostVolunteerForm = new DetailPostVolunteerForm(postIdTop3, userId);
            detailPostVolunteerForm.setVisible(true);
            detailPostVolunteerForm.setLocationRelativeTo(null);
            detailPostVolunteerForm.pack();
            detailPostVolunteerForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else { 
            JOptionPane.showMessageDialog(null, "Hãy đăng nhập để xem chi tiết bài viết chi tiết");
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            loginForm.setLocationRelativeTo(null);
            loginForm.pack();
            loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } 
    }//GEN-LAST:event_titlePostTop3MouseClicked

    private void searchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusGained
        searchField.setText("");
    }//GEN-LAST:event_searchFieldFocusGained

    private void searchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusLost
        searchField.setText("Tìm kiếm hoạt động");
    }//GEN-LAST:event_searchFieldFocusLost

    private void searchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyTyped
        String keyword = searchField.getText();
        
        if(!keyword.equals("")) { 
            String query = "select image,title,id from posts " +
                        "where title like '%" + keyword + "%' limit 1";
            Statement st;
            ResultSet rs;


            try {
                st = MyConnection.getConnection().createStatement();

                rs = st.executeQuery(query);

                if(rs.next()) { 
                    loadImage(rs.getBlob(1), imageAttention, titleAttention, rs.getString(2));
                    postIdAttention = rs.getInt(3);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_searchFieldKeyTyped

    private void labelAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAboutMouseClicked
        if(userId > 0) { 
            AboutForm aboutForm = new AboutForm(userId);
            aboutForm.setVisible(true);
            aboutForm.setLocationRelativeTo(null);
            aboutForm.pack();
            aboutForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else { 
            AboutForm aboutForm = new AboutForm();
            aboutForm.setVisible(true);
            aboutForm.setLocationRelativeTo(null);
            aboutForm.pack();
            aboutForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_labelAboutMouseClicked

    private void comboBoxDirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDirectionActionPerformed
        int index = comboBoxDirection.getSelectedIndex();

        if(index == 0) { 
            ProfileForm profileForm = new ProfileForm(userId, "");
            profileForm.setVisible(true);
            profileForm.pack();
            profileForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else if (index == 1) { 
            ManageUserPost manageUserPost = new ManageUserPost(userId);
            manageUserPost.setVisible(true);
            manageUserPost.pack();
            manageUserPost.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else if (index == 2 ) { 
            CreatePost createPostForm = new CreatePost(userId);
            createPostForm.setVisible(true);
            createPostForm.pack();
            createPostForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else { 
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            loginForm.pack();
            loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_comboBoxDirectionActionPerformed

    private void labelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseClicked
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        loginForm.pack();
        loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public void loadListPost() { 
        PreparedStatement ps;
        ResultSet rs;
        String query = "select image,title,id from posts " +
                        "order by created_at desc limit 3";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            rs = ps.executeQuery();
            rs.next();
            loadImage(rs.getBlob(1), labelImageTop1, titlePostTop1, rs.getString(2));
            postIdTop1 = rs.getInt(3);
            rs.next();
            loadImage(rs.getBlob(1), labelImageTop2, titlePostTop2, rs.getString(2));
            postIdTop2 = rs.getInt(3);
            rs.next();
            loadImage(rs.getBlob(1), labelImageTop3, titlePostTop3, rs.getString(2));
            postIdTop3 = rs.getInt(3);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void loadImage(Blob imagePost, JLabel label, JLabel title, String text) { 
        ImageIcon myImage = null;
        byte[] imageBytes = null;
        if(imagePost != null) { 
            try {
                imageBytes = imagePost.getBytes(1, (int) imagePost.length());
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            myImage = new ImageIcon(imageBytes);
        } else { 
            File nullImagePost = new File(System.getProperty("user.dir") + "/src/images/image-post-null.jpg");
            String path = nullImagePost.getAbsolutePath();
            myImage = new ImageIcon(path);
        }
        Image image = myImage.getImage();
        Image newImage = image.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(newImage);
        label.setIcon(imageIcon);
        title.setText(text);
    }
    public void loadPostAttention() { 
        PreparedStatement ps;
        ResultSet rs;
        String query = "select post_id, COUNT(post_id) as SL, title,image from user_ref_posts " +
                        "inner join posts " +
                        "on posts.id = user_ref_posts.post_id " +
                        "group by post_id order by sl limit 1";
        try {
            
            
            ps = MyConnection.getConnection().prepareStatement(query);
            rs = ps.executeQuery();
            if(rs.next()) { 
                postIdAttention = rs.getInt(1);
                titleAttention.setText(rs.getString(3));
                ImageIcon myImage = null;
                if(rs.getBlob(4)!= null) { 
                    Blob imagePost = rs.getBlob(4);
                    byte[] imageBytes = imagePost.getBytes(1, (int) imagePost.length());
                    myImage = new ImageIcon(imageBytes);
                } else { 
                    File nullAvatar = new File(System.getProperty("user.dir") + "/src/images/image-post-null.jpg");
                    String path = nullAvatar.getAbsolutePath();
                    myImage = new ImageIcon(path);
                }
                Image image = myImage.getImage();
                Image newImage = image.getScaledInstance(imageAttention.getWidth(), imageAttention.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(newImage);
                imageAttention.setIcon(imageIcon);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public  void loadLogo() { 
        File logo = new File(System.getProperty("user.dir") + "/src/images/logo.jpg");
        String path = logo.getAbsolutePath();
        ImageIcon myImage = new ImageIcon(path);
        
        Image image = myImage.getImage();
        Image newImage = image.getScaledInstance(labelLogo.getWidth(), labelLogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(newImage);
        labelLogo.setIcon(imageIcon);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxDirection;
    private javax.swing.JLabel imageAttention;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAbout;
    private javax.swing.JLabel labelHome;
    private javax.swing.JLabel labelImageTop1;
    private javax.swing.JLabel labelImageTop2;
    private javax.swing.JLabel labelImageTop3;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel titleAttention;
    private javax.swing.JLabel titlePostTop1;
    private javax.swing.JLabel titlePostTop2;
    private javax.swing.JLabel titlePostTop3;
    // End of variables declaration//GEN-END:variables
}
