/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import connect_db.MyConnection;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Donation;
import models.PostVolunteer;

/**
 *
 * @author PHUTRAN
 */
public class ManagePost extends javax.swing.JFrame {

    /**
     * Creates new form ManagePost
     */
    ArrayList<Donation> listDonations = new ArrayList<>();
    ArrayList<PostVolunteer> listPostVolunteers = new ArrayList<>();
    
    public ManagePost() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Quản lý các hoạt động");
        btnDeleteDonation.setVisible(false);
        btnDeleteVolunteer.setVisible(false);
        
        totalProjectDonation.setEnabled(false);
        totalProjectVolunteer.setEnabled(false);
        goalMoney.setEnabled(false);
        goalPeople.setEnabled(false);
        raiseMoneyField.setEnabled(false);
        raisePeopleField.setEnabled(false);
        
        
        loadLogo();
        loadTitleDonation();
        loadTitleVolunteer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelManagePost = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalProjectDonation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboBoxTitleDonation = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        goalMoney = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        raiseMoneyField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDonation = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePeopleVolunteerSignUp = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        totalProjectVolunteer = new javax.swing.JTextField();
        comboBoxTitleVolunteer = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        goalPeople = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        raisePeopleField = new javax.swing.JTextField();
        btnDeleteDonation = new javax.swing.JButton();
        btnDeleteVolunteer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(189, 213, 234));

        labelLogo.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Đăng xuất");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        labelManagePost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelManagePost.setText("Hoạt động");
        labelManagePost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Người dùng");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setText("Nguồn tiền và tình nguyện viên");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addGap(20, 20, 20)
                .addComponent(labelManagePost)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(labelManagePost)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14))
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(189, 213, 234));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản lý hoạt động");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Danh sách các hoạt động từ thiện");

        jLabel5.setText("Tổng số dự án:");

        jLabel6.setText("Tên dự án:");

        comboBoxTitleDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTitleDonationActionPerformed(evt);
            }
        });

        jLabel7.setText("Số tiền huy động quyên góp:");

        jLabel8.setText("Số tiền đã quyên góp:");

        tableDonation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và tên người quyên góp", "Số tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDonation);
        if (tableDonation.getColumnModel().getColumnCount() > 0) {
            tableDonation.getColumnModel().getColumn(0).setResizable(false);
            tableDonation.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Danh sách các hoạt động tình nguyện");

        tablePeopleVolunteerSignUp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và tên người đăng ký"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablePeopleVolunteerSignUp);
        if (tablePeopleVolunteerSignUp.getColumnModel().getColumnCount() > 0) {
            tablePeopleVolunteerSignUp.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel10.setText("Tổng số dự án:");

        comboBoxTitleVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTitleVolunteerActionPerformed(evt);
            }
        });

        jLabel11.setText("Tên dự án:");

        jLabel12.setText("Số người huy động:");

        jLabel13.setText("Số người đã đăng ký:");

        btnDeleteDonation.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteDonation.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteDonation.setText("X");
        btnDeleteDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDonationActionPerformed(evt);
            }
        });

        btnDeleteVolunteer.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteVolunteer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteVolunteer.setText("X");
        btnDeleteVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVolunteerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxTitleDonation, 0, 226, Short.MAX_VALUE)
                            .addComponent(goalMoney)
                            .addComponent(raiseMoneyField)
                            .addComponent(totalProjectDonation, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(137, 137, 137)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalProjectVolunteer)
                            .addComponent(goalPeople, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(raisePeopleField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboBoxTitleVolunteer, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteDonation)
                    .addComponent(btnDeleteVolunteer))
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(totalProjectDonation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboBoxTitleDonation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteDonation))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(goalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(raiseMoneyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(totalProjectVolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTitleVolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btnDeleteVolunteer))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(goalPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(raisePeopleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxTitleDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTitleDonationActionPerformed
        DecimalFormat formatter = new DecimalFormat("#,###.00");
        
        raiseMoneyField.setText("0");
        
        DefaultTableModel tableModelDonation = (DefaultTableModel) tableDonation.getModel();
        tableModelDonation.setRowCount(0);
        
        String itemSelected = (String) comboBoxTitleDonation.getSelectedItem();
        Donation donationSelected = findDonationSelected(listDonations, itemSelected);
        
        goalMoney.setText(formatter.format(donationSelected.getMoney()));
        
        PreparedStatement ps;
        ResultSet rs;
        String query = "select goal_money, raise_money, full_name, donate_money " +
                        "from posts as post " +
                        "inner join user_ref_posts as urp " +
                        "on post.id = urp.post_id " +
                        "inner join users as user " +
                        "on urp.user_id = user.id " +
                        "where post.id = ?" ;
        if(donationSelected != null) {
            btnDeleteDonation.setVisible(true);
            try {
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.setInt(1, donationSelected.getId());
                rs = ps.executeQuery();

                while(rs.next()) { 
                    goalMoney.setText(formatter.format(rs.getDouble(1)));
                    raiseMoneyField.setText(formatter.format(rs.getDouble(2)));
                    tableModelDonation.addRow(new Object[] { 
                        rs.getString(3),
                        rs.getDouble(4),
                    });
                }
            } catch (SQLException ex) {
                Logger.getLogger(ManagePost.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_comboBoxTitleDonationActionPerformed

    private void btnDeleteDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDonationActionPerformed
        String itemSelected = (String) comboBoxTitleDonation.getSelectedItem();
        int indexItemSelected = comboBoxTitleDonation.getSelectedIndex();
        Donation donationSelected = findDonationSelected(listDonations, itemSelected);
        
        Statement st;
        String queryDeleteDonationPost = "delete from posts where id = " + donationSelected.getId();
        int result = 0;
        try {
            st = MyConnection.getConnection().createStatement();
            result = st.executeUpdate(queryDeleteDonationPost);
            if(result == 1) { 
                JOptionPane.showMessageDialog(null, "Xoá bài viết quyên góp thành công", "Delete donation post sucess", 2);
                comboBoxTitleDonation.removeItemAt(indexItemSelected);
            } else { 
                JOptionPane.showMessageDialog(null, "Xoá bài viết quyên góp thất bại", "Delete donation post failed", 2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManagePost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteDonationActionPerformed

    private void comboBoxTitleVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTitleVolunteerActionPerformed
        DecimalFormat formatter = new DecimalFormat("#,###");
        
        
        raisePeopleField.setText("0");
        goalPeople.setText("0");
        
        String itemSelected = (String) comboBoxTitleVolunteer.getSelectedItem();
        
        DefaultTableModel tableModelVolunteer = (DefaultTableModel) tablePeopleVolunteerSignUp.getModel();
        tableModelVolunteer.setRowCount(0);
  
        PostVolunteer postVolunteerSelected = findPostVolunteerSelected(listPostVolunteers, itemSelected);
        goalPeople.setText(formatter.format(postVolunteerSelected.getGoalPeople()));

        PreparedStatement ps;
        ResultSet rs;
        
        String queryGetPostVolunteer = "select goal_people, raise_people, full_name " +
                                        "from posts as post " +
                                        "inner join user_ref_posts as urp " +
                                        "on post.id = urp.post_id " +
                                        "inner join users as user " +
                                        "on urp.user_id = user.id " +
                                        "where post.id = ?";
        if(postVolunteerSelected != null) { 
            btnDeleteVolunteer.setVisible(true);
            try {
                ps = MyConnection.getConnection().prepareStatement(queryGetPostVolunteer);
                ps.setInt(1, postVolunteerSelected.getId());
                rs = ps.executeQuery();
                while(rs.next()) { 
                    goalPeople.setText(formatter.format(rs.getInt(1)));
                    raisePeopleField.setText(formatter.format(rs.getInt(2)));
                    tableModelVolunteer.addRow(new Object[] { 
                        rs.getString(3),
                    });
                }
            } catch (SQLException ex) {
                Logger.getLogger(ManagePost.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_comboBoxTitleVolunteerActionPerformed

    private void btnDeleteVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVolunteerActionPerformed
        String itemSelected = (String) comboBoxTitleVolunteer.getSelectedItem();
        int indexItemSelected = comboBoxTitleVolunteer.getSelectedIndex();
        
        PostVolunteer postVolunteerSelected = findPostVolunteerSelected(listPostVolunteers, itemSelected);
        
        Statement st;
        String queryDeletePostVolunteer = "delete from posts where id = " + postVolunteerSelected.getId();
        int result = 0;
        try {
            st = MyConnection.getConnection().createStatement();
            result = st.executeUpdate(queryDeletePostVolunteer);
            if(result == 1) { 
                JOptionPane.showMessageDialog(null, "Xoá bài viết tình nguyện thành công", "Delete volunteer post sucess", 2);
                comboBoxTitleVolunteer.removeItemAt(indexItemSelected);
            } else { 
                JOptionPane.showMessageDialog(null, "Xoá bài viết tình nguyện thất bại", "Delete volunteer post failed", 2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManagePost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteVolunteerActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        ManageUserForm manageUserForm = new ManageUserForm();
        manageUserForm.setVisible(true);
        manageUserForm.setLocationRelativeTo(null);
        manageUserForm.pack();
        manageUserForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        loginForm.setLocationRelativeTo(null);
        loginForm.pack();
        loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        ManageDonateAndPeopleJoinForm manageDonateAndPeopleJoinForm = new ManageDonateAndPeopleJoinForm();
        manageDonateAndPeopleJoinForm.setVisible(true);
        manageDonateAndPeopleJoinForm.setLocationRelativeTo(null);
        manageDonateAndPeopleJoinForm.pack();
        manageDonateAndPeopleJoinForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public void loadTitleVolunteer() { 
        String queryTitleVolunteer = "select post.id, title, goal_people from posts as post " +
                                    "inner join users as user " +
                                    "on post.user_id = user.id " +
                                    "where goal_people > 0";
        
        Statement st;
        ResultSet rs;
        
        try {
            st = MyConnection.getConnection().createStatement();
            rs = st.executeQuery(queryTitleVolunteer);
            
            while(rs.next()) { 
                PostVolunteer postVolunteer = new PostVolunteer(rs.getInt(1), rs.getString(2), rs.getDouble(3));
                listPostVolunteers.add(postVolunteer);
            }
            totalProjectVolunteer.setText(String.valueOf(listPostVolunteers.size()));
            for (PostVolunteer postVolunteer : listPostVolunteers) {
                comboBoxTitleVolunteer.addItem(postVolunteer.getTitle());
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManagePost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public Donation findDonationSelected(ArrayList<Donation> donations, String title) { 
        for (Donation donation : donations) {
            if(donation.getTitle().equals(title)) { 
                return donation;
            }
        }
        return null;
    }
    public PostVolunteer findPostVolunteerSelected(ArrayList<PostVolunteer> postVolunteers, String title) { 
        for (PostVolunteer postVolunteer : postVolunteers) {
            if(postVolunteer.getTitle().equals(title)) { 
                return postVolunteer;
            }
        }
        return null;
    }
    public void loadTitleDonation() { 
        String queryTitleDonation = "select id, title, goal_money from posts " +
                                    "where goal_money > 0";
        Statement st;
        ResultSet rs;
        try {
            st = MyConnection.getConnection().createStatement();
            rs = st.executeQuery(queryTitleDonation);
            while(rs.next()) { 
                Donation donation = new Donation(rs.getInt(1),rs.getString(2), rs.getDouble(3));
                listDonations.add(donation);
            }
            totalProjectDonation.setText(String.valueOf(listDonations.size()));
            
            for (Donation donation : listDonations) {
                    comboBoxTitleDonation.addItem(donation.getTitle());
            }
            return;
        } catch (SQLException ex) {
            Logger.getLogger(ManagePost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public  void loadLogo() { 
        File logo = new File(System.getProperty("user.dir") + "/src/images/logo.jpg");
        String path = logo.getAbsolutePath();
        ImageIcon myImage = new ImageIcon(path);
        
        Image image = myImage.getImage();
        Image newImage = image.getScaledInstance(labelLogo.getWidth(), labelLogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(newImage);
        labelLogo.setIcon(imageIcon);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteDonation;
    private javax.swing.JButton btnDeleteVolunteer;
    private javax.swing.JComboBox<String> comboBoxTitleDonation;
    private javax.swing.JComboBox<String> comboBoxTitleVolunteer;
    private javax.swing.JTextField goalMoney;
    private javax.swing.JTextField goalPeople;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelManagePost;
    private javax.swing.JTextField raiseMoneyField;
    private javax.swing.JTextField raisePeopleField;
    private javax.swing.JTable tableDonation;
    private javax.swing.JTable tablePeopleVolunteerSignUp;
    private javax.swing.JTextField totalProjectDonation;
    private javax.swing.JTextField totalProjectVolunteer;
    // End of variables declaration//GEN-END:variables
}
